# -*- coding: utf-8 -*-
"""crazy test.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OzZ54RIfdMyiDzhsSKQ1apDY0bJfT4SA
"""

!pip install -q trafilatura ftfy beautifulsoup4 requests

import re
import os
import zipfile
import shutil
import calendar
import requests
import trafilatura
from ftfy import fix_text
from bs4 import BeautifulSoup
from urllib.parse import urljoin
from google.colab import files

ARCHIVE_URL = "https://www.churchofjesuschrist.org/study/general-conference/19711979?lang=eng"
COLLECTED_BY = "Samuel Baird"
COLLECTED_DATE = "2026-03-24"
OUTPUT_EXT = ".md"
ROOT_OUTPUT_FOLDER = "general_conference_archive_output"
ZIP_NAME = "general_conference_archive.zip"

HEADERS = {"User-Agent": "Mozilla/5.0"}

def clean_inline(text):
    if not text:
        return ""
    text = fix_text(text)
    text = text.replace("\xa0", " ")
    text = re.sub(r"[ \t]+", " ", text)
    return text.strip()

def clean_block_text(text):
    if not text:
        return ""
    text = fix_text(text)
    text = text.replace("\r\n", "\n").replace("\r", "\n")
    text = text.replace("\xa0", " ")
    text = re.sub(r"[ \t]+", " ", text)
    text = re.sub(r"\n{3,}", "\n\n", text)
    return text.strip()

def slugify(text):
    text = clean_inline(text).lower()
    text = re.sub(r"[^\w\s-]", "", text)
    text = re.sub(r"[-\s]+", "-", text)
    return text.strip("-")

def short_title_slug(title):
    words = re.findall(r"[A-Za-z0-9']+", clean_inline(title).lower())
    stop = {"a", "an", "the", "and", "or", "of", "to", "in", "on", "for", "with"}
    words = [w for w in words if w not in stop] or words
    return "-".join(words[:6]) if words else "untitled"

def speaker_filename(name):
    if not name:
        return "unknown-unknown"
    name = re.sub(r"\b(Elder|President|Bishop|Sister|Brother)\b\.?", "", clean_inline(name))
    parts = [p for p in name.split() if p]
    if len(parts) < 2:
        return "unknown-unknown"
    return f"{slugify(parts[-1])}-{slugify(parts[0])}"

def safe_folder_name(name):
    name = clean_inline(name)
    name = re.sub(r'[<>:"/\\|?*]', "", name)
    return name.strip()

def infer_date(url, session):
    m = re.search(r"/general-conference/(\d{4})/(\d{2})/", url)
    if not m:
        return None
    year, month = int(m.group(1)), int(m.group(2))
    cal = calendar.monthcalendar(year, month)
    sat = next(week[calendar.SATURDAY] for week in cal if week[calendar.SATURDAY])
    sun = sat + 1
    s = (session or "").lower()

    if "saturday" in s:
        return f"{year}-{month:02d}-{sat:02d}"
    if "sunday" in s:
        return f"{year}-{month:02d}-{sun:02d}"
    if "priesthood" in s or "women" in s or "young women" in s or "relief society" in s:
        return f"{year}-{month:02d}-{sat:02d}"

    return None

def q(x):
    return "null" if x is None else '"' + str(x).replace("\\", "\\\\").replace('"', '\\"') + '"'

def get_soup(url):
    res = requests.get(url, headers=HEADERS, timeout=30)
    res.raise_for_status()
    res.encoding = res.apparent_encoding
    return BeautifulSoup(res.text, "html.parser"), res.text

def find_top_title_and_conference(soup):
    h1 = soup.find("h1")
    title = clean_inline(h1.get_text(" ", strip=True)) if h1 else "Untitled"

    conference = None

    if h1:
        nearby = []
        for el in h1.find_all_next(["p", "div", "span", "a"], limit=12):
            txt = clean_inline(el.get_text(" ", strip=True))
            if not txt:
                continue
            if txt == title:
                continue
            nearby.append(txt)

        for txt in nearby:
            if "general conference" in txt.lower() and len(txt.split()) <= 6:
                conference = txt
                break

        if not conference:
            for txt in nearby[:4]:
                if "conference" in txt.lower():
                    conference = txt
                    break

    if conference:
        conference = clean_inline(conference)
        if len(conference.split()) > 8:
            conference = None

    return title, conference

def find_speaker(soup):
    for el in soup.find_all(["p", "div", "span"]):
        txt = clean_inline(el.get_text(" ", strip=True))
        if txt.lower().startswith("by "):
            txt = txt.split("\n")[0]
            txt = re.split(r"(?i)\bacting president\b|\bof the quorum\b", txt)[0].strip()
            return clean_inline(txt[3:])
    return None

def find_session_from_nav(soup, title):
    session_patterns = [
        "Saturday Morning Session",
        "Saturday Afternoon Session",
        "Saturday Evening Session",
        "Sunday Morning Session",
        "Sunday Afternoon Session",
        "Priesthood Session",
        "Women's Session",
        "Young Women Session",
        "Relief Society Session",
    ]

    texts = []
    for el in soup.find_all(["a", "div", "span", "p", "li"]):
        txt = clean_inline(el.get_text(" ", strip=True))
        if txt:
            texts.append(txt)

    talk_index = None
    for i, txt in enumerate(texts):
        if txt == title:
            talk_index = i
            break

    if talk_index is None:
        return None

    for j in range(talk_index - 1, -1, -1):
        for sess in session_patterns:
            if texts[j].lower() == sess.lower():
                return sess

    for j in range(talk_index - 1, -1, -1):
        if "session" in texts[j].lower():
            return texts[j]

    return None

def extract_transcript(html_text, source_title, conference, speaker, session):
    raw_text = trafilatura.extract(
        html_text,
        include_comments=False,
        include_tables=False,
        include_links=False,
        include_images=False,
        favor_precision=True,
        output_format="txt"
    )

    if not raw_text:
        soup = BeautifulSoup(html_text, "html.parser")
        paragraphs = []
        for p in soup.find_all("p"):
            txt = clean_inline(p.get_text(" ", strip=True))
            if txt:
                paragraphs.append(txt)

        if not paragraphs:
            raise RuntimeError("Could not extract article text.")

        raw_lines = paragraphs
    else:
        raw_text = clean_block_text(raw_text)
        raw_lines = [clean_inline(x) for x in raw_text.split("\n") if clean_inline(x)]

    start_idx = 0
    for i, line in enumerate(raw_lines):
        if line == source_title:
            start_idx = i + 1
            break

    transcript_lines = []
    for line in raw_lines[start_idx:]:
        low = line.lower()

        if low in {"notes", "related content", "footnotes"}:
            break
        if line == source_title:
            continue
        if conference and line == conference:
            continue
        if speaker and (line == speaker or line == f"By {speaker}"):
            continue
        if session and line == session:
            continue
        if re.match(r"^\d+\.", line):
            break

        transcript_lines.append(line)

    while transcript_lines and (
        transcript_lines[0].lower().startswith("by ")
        or transcript_lines[0] == speaker
        or transcript_lines[0] == conference
        or transcript_lines[0] == session
    ):
        transcript_lines.pop(0)

    transcript = "\n\n".join(transcript_lines).strip()

    if not transcript:
        raise RuntimeError("Transcript came back empty after cleaning.")

    return transcript

def extract_conference_links(archive_url):
    soup, _ = get_soup(archive_url)
    links = []

    for a in soup.find_all("a", href=True):
        label = clean_inline(a.get_text(" ", strip=True))
        href = a["href"].strip()
        full = urljoin("https://www.churchofjesuschrist.org", href)

        if not re.fullmatch(r"(April|October)\s+\d{4}", label):
            continue

        m = re.search(r"/study/general-conference/(\d{4})/(\d{2})(?:[/?#]|$)", full)
        if not m:
            continue

        year = int(m.group(1))
        month = int(m.group(2))
        if month not in {4, 10}:
            continue

        normalized = f"https://www.churchofjesuschrist.org/study/general-conference/{year}/{month:02d}?lang=eng"
        links.append((year, month, label, normalized))

    seen = set()
    unique = []
    for year, month, label, url in links:
        if url not in seen:
            seen.add(url)
            unique.append((year, month, label, url))

    unique.sort(key=lambda x: (x[0], x[1]), reverse=True)

    print("Conference links found:")
    for _, _, label, url in unique:
        print(f"  {label} -> {url}")

    return [url for _, _, _, url in unique]

def extract_talk_links(conference_url):
    soup, _ = get_soup(conference_url)
    links = []

    for a in soup.find_all("a", href=True):
        href = a["href"]
        full = urljoin("https://www.churchofjesuschrist.org", href)

        if "/study/general-conference/" not in full:
            continue

        m = re.search(r"/study/general-conference/\d{4}/\d{2}/([^/?#]+)", full)
        if not m:
            continue

        slug = m.group(1)

        # NEW LOGIC: allow both modern AND older talk URLs
        if len(slug) < 3:
            continue

        # Skip obvious non-talk pages
        if any(x in slug.lower() for x in [
            "session", "contents", "index", "video", "topics"
        ]):
            continue

        if "lang=" not in full:
            full += "&lang=eng" if "?" in full else "?lang=eng"

        links.append(full)

    # dedupe
    seen = set()
    unique = []
    for link in links:
        norm = link.rstrip("/")
        if norm not in seen:
            seen.add(norm)
            unique.append(link)

    return unique

def conference_name_from_url(url):
    m = re.search(r"/general-conference/(\d{4})/(\d{2})", url)
    if not m:
        return "Unknown Conference"
    year = m.group(1)
    month_num = int(m.group(2))
    month_name = calendar.month_name[month_num]
    return f"{month_name} {year}"

def scrape_talk(url):
    soup, html_text = get_soup(url)

    source_title, conference = find_top_title_and_conference(soup)
    speaker = find_speaker(soup)
    session = find_session_from_nav(soup, source_title)

    if not conference:
        m = re.search(r"/general-conference/(\d{4})/(\d{2})/", url)
        if m:
            year = m.group(1)
            month_num = int(m.group(2))
            month_name = calendar.month_name[month_num]
            conference = f"{month_name} {year} General Conference"

    if not speaker:
        m = re.search(r"/study/general-conference/\d{4}/\d{2}/([^/?#]+)", url)
        if m:
            slug = re.sub(r"^\d+", "", m.group(1))
            speaker = slug.replace("-", " ").title()

    date_val = infer_date(url, session) or "UNKNOWN-DATE"
    transcript = extract_transcript(html_text, source_title, conference, speaker, session)

    yaml_text = f"""---
# === IDENTIFICATION ===
speaker: {q(speaker)}
date: {q(date_val)}
conference: {q(conference)}
session: {q(session)}                     # e.g., "Saturday Morning", "Priesthood", "Sunday Afternoon"

# === SOURCE & PROVENANCE ===
source_title: {q(source_title)}
source_url: {q(url)}
source_type: "church_website"
fidelity: "verbatim"
fidelity_notes: "Copied from the official Church website."

# === COLLECTION METADATA ===
collected_by: {q(COLLECTED_BY)}
collected_date: {q(COLLECTED_DATE)}
needs_review: true                # set false once a second person has verified
notes: "This website was scraped by Samuel Baird. Script: https://github.com/Samuel-Baird/pulpit"
---

{transcript}
"""

    filename = f"{date_val}_{speaker_filename(speaker)}_{short_title_slug(source_title)}{OUTPUT_EXT}"
    return filename, yaml_text

if os.path.exists(ROOT_OUTPUT_FOLDER):
    shutil.rmtree(ROOT_OUTPUT_FOLDER)
os.makedirs(ROOT_OUTPUT_FOLDER, exist_ok=True)

conference_links = extract_conference_links(ARCHIVE_URL)
print(f"\nFound {len(conference_links)} conference links total")

all_saved_files = []
all_failed = []

for conf_index, conf_url in enumerate(conference_links, start=1):
    conf_folder_name = safe_folder_name(conference_name_from_url(conf_url))
    conf_folder_path = os.path.join(ROOT_OUTPUT_FOLDER, conf_folder_name)
    os.makedirs(conf_folder_path, exist_ok=True)

    print(f"\n[{conf_index}/{len(conference_links)}] Conference: {conf_folder_name}")
    talk_links = extract_talk_links(conf_url)
    print(f"  Found {len(talk_links)} talk links")

    for talk_index, link in enumerate(talk_links, start=1):
        try:
            filename, content = scrape_talk(link)
            path = os.path.join(conf_folder_path, filename)

            with open(path, "w", encoding="utf-8") as f:
                f.write(content)

            all_saved_files.append(path)
            print(f"    [{talk_index}/{len(talk_links)}] Saved: {filename}")

        except Exception as e:
            all_failed.append((link, str(e)))
            print(f"    [{talk_index}/{len(talk_links)}] FAILED: {link}")
            print(f"       {e}")

with zipfile.ZipFile(ZIP_NAME, "w", zipfile.ZIP_DEFLATED) as zf:
    for root, _, filenames in os.walk(ROOT_OUTPUT_FOLDER):
        for filename in filenames:
            full_path = os.path.join(root, filename)
            arcname = os.path.relpath(full_path, ROOT_OUTPUT_FOLDER)
            zf.write(full_path, arcname=arcname)

print("\nDone.")
print(f"Saved {len(all_saved_files)} files total")
print(f"Failed {len(all_failed)} files total")

if all_failed:
    print("\nFailures:")
    for link, err in all_failed[:20]:
        print("-", link)
        print(" ", err)
    if len(all_failed) > 20:
        print(f"... and {len(all_failed) - 20} more")

files.download(ZIP_NAME)